CREATE TABLE CIUDADES(
    CODIGO INTEGER PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR2 NOT NULL
);


CREATE TABLE EQUIPOS(
    CODIGO INTEGER PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR2 NOT NULL,
    SIGLAS VARCHAR2 NOT NULL,
    COD_CIUDAD INTEGER NOT NULL,
    VECES_CAMPEON INTEGER DEFAULT 0,
    VECES_SUBCAMPEON INTEGER DEFAULT 0,
    ULTIMO_ANIO NOT NULL
);